<div id="createAirportModal" role="dialog" class="fixed inset-0 z-[9000] hidden flex items-center justify-center bg-slate-950/50 p-4 airport-overlay">
 <div class="w-full max-w-xl overflow-hidden rounded-xl bg-white shadow-2xl">
  <header class="flex items-center gap-3 bg-gradient-to-r from-blue-700 to-indigo-600 px-5 py-4 text-white"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-white/15"><i class="fas fa-plane-departure"></i></span><div><h2 class="text-sm font-bold">Add Airport</h2><p class="text-[11px] text-blue-100">Register airport location and IATA code</p></div><button type="button" class="modal-close-create ml-auto h-8 w-8 rounded-lg bg-white/15"><i class="fas fa-times"></i></button></header>
  <form id="createStateForm" action="{{ route('role.airport.store',['role'=>Str::slug(Auth::user()->getRoleNames()->first())]) }}" class="grid gap-4 p-5 sm:grid-cols-2">@csrf
   <label><span class="mb-1 block text-xs font-semibold text-slate-600">Country <b class="text-red-500">*</b></span><select id="create_country_id" onchange="getStates(this,'#create_state_id')" data-action="{{ route('role.get-states-by-country',['role'=>Str::slug(Auth::user()->getRoleNames()->first())]) }}" class="form-select select2 w-full"><option value="">Select Country</option>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }}</option>@endforeach</select><p id="create_country_msg" class="error-message mt-1 hidden text-xs text-red-500">Please select a country</p></label>
   <label><span class="mb-1 block text-xs font-semibold text-slate-600">State <b class="text-red-500">*</b></span><select id="create_state_id" class="form-select select2 w-full"><option value="">Select State</option></select><p id="create_state_msg" class="error-message mt-1 hidden text-xs text-red-500">Please select a state</p></label>
   <label><span class="mb-1 block text-xs font-semibold text-slate-600">Airport Name <b class="text-red-500">*</b></span><input id="create_name" class="form-input h-10 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" placeholder="e.g. Hazrat Shahjalal International Airport"><p class="error-message mt-1 hidden text-xs text-red-500">Please enter an airport name</p></label>
   <label><span class="mb-1 block text-xs font-semibold text-slate-600">IATA Code <b class="text-red-500">*</b></span><input id="create_code" maxlength="10" class="form-input h-10 w-full rounded-lg border border-slate-300 px-3 text-sm uppercase focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" placeholder="e.g. DAC"><p class="error-message mt-1 hidden text-xs text-red-500">Please enter an airport code</p></label>
  </form>
  <footer class="flex justify-end gap-2 border-t bg-slate-50 px-5 py-3"><button type="button" class="modal-close-create rounded-lg border px-4 py-2 text-xs font-semibold text-slate-600">Cancel</button><button id="createStateSubmit" type="button" class="rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white"><i class="fas fa-floppy-disk mr-1"></i>Save Airport</button></footer>
 </div>
</div>
