<?php

namespace App\Jobs;

use App\Models\EmployeeSalary;
use App\Models\User;
use App\Services\PayrollService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

/**
 * Generates one employee's salary + payslip for one month and sends the
 * payslip-generated notifications (in-app, push, email, SMS — see
 * PayrollService::sendPayslipNotifications()). Dispatched per employee by
 * the payroll:generate-monthly scheduled command so a failure for one
 * employee doesn't block the rest and can be retried independently.
 */
class GenerateMonthlyPayslip implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public int $tries = 3;

    public function __construct(
        public int $userId,
        public int $year,
        public int $month,
    ) {
        // Its own named queue (assigned here, not as a redeclared property —
        // PHP treats even a differing default value as an incompatible
        // property redefinition against Queueable's own $queue) so it can be
        // worked in isolation from unrelated queued jobs (e.g. chat broadcast
        // events) without needing every job type in the app to be sorted
        // through together.
        $this->onQueue('payroll');
    }

    public function handle(PayrollService $payroll): void
    {
        $user = User::find($this->userId);
        if (!$user) {
            return;
        }

        $monthStr = str_pad((string) $this->month, 2, '0', STR_PAD_LEFT);

        // Idempotency guard — safe to re-run/retry without double-generating.
        // Only wraps the payslip block (not a `return`) so a retry that finds
        // this month's payslip already created still gets a chance to run
        // the anniversary-reconciliation check below.
        if (!EmployeeSalary::where('user_id', $user->id)->where('year', $this->year)->where('month', $monthStr)->exists()) {
            $calc = $payroll->calculateAttendanceDeductions($user, $this->year, $this->month);

            $grossSalary = (float) ($calc['gross_salary'] ?? 0);
            if ($grossSalary <= 0) {
                Log::warning('Skipped monthly payroll generation — no gross salary on file.', ['user_id' => $user->id]);
                return;
            }

            $netSalary = round($grossSalary + $calc['overtime_salary'] - $calc['total_deductions'], 2);

            $empSalary = $payroll->createEmployeeSalaryRecord([
                'user_id' => $user->id,
                'loan_id' => $calc['loan_id'],
                'advance_salary_id' => $calc['advance_salary_id'],
                'month' => $monthStr,
                'year' => $this->year,
                'gross_salary' => $grossSalary,
                'loan_deduction' => $calc['loan_deduction'],
                'advance_salary_deduction' => $calc['advance_salary'],
                'early_leave_deduction' => $calc['early_out_deduction'],
                'over_time_days' => $calc['summary']['overtime_days'] ?? 0,
                'over_time' => $calc['summary']['overtime_minutes'] ?? 0,
                'overtime_salary' => $calc['overtime_salary'],
                'absent_deduction' => $calc['absent_deduction'],
                'leave_deduction' => $calc['leave_deduction'],
                'late_deduction' => $calc['late_deduction'],
                'total_deductions' => $calc['total_deductions'],
                'net_salary' => $netSalary,
                'salary_generation_date' => now()->toDateString(),
                'scheduled_date' => now()->addDays(5)->toDateString(),
                'status' => 'Pending',
                'notes' => 'Auto-generated by monthly payroll run',
            ]);

            ['payslip' => $payslip] = $payroll->issuePayslip($empSalary);

            $payroll->sendPayslipNotifications($empSalary, $payslip);
        }

        // No-ops unless this month is $user's service-anniversary month and
        // that service year hasn't already been reconciled — safe to call on
        // every run.
        $payroll->maybeProcessAnniversaryReconciliation($user, $this->year, $this->month);
    }
}
