<div id="createStateModal" role="dialog" class="fixed inset-0 z-[9000] hidden flex items-center justify-center bg-slate-950/50 p-4 state-overlay">
 <div class="w-full max-w-lg overflow-hidden rounded-xl bg-white shadow-2xl">
  <header class="flex items-center gap-3 bg-gradient-to-r from-blue-700 to-indigo-600 px-5 py-4 text-white"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-white/15"><i class="fas fa-map-location-dot"></i></span><div><h2 class="text-sm font-bold">Add State</h2><p class="text-[11px] text-blue-100">Create a state under an existing country</p></div><button type="button" class="modal-close-create ml-auto h-8 w-8 rounded-lg bg-white/15"><i class="fas fa-times"></i></button></header>
  <form id="createStateForm" action="{{ route('role.states.store',['role'=>Str::slug(Auth::user()->getRoleNames()->first())]) }}" class="grid gap-4 p-5">@csrf
   <label><span class="mb-1 block text-xs font-semibold text-slate-600">Country <b class="text-red-500">*</b></span><select id="create_country_id" class="form-select select2 w-full">@foreach($countries as $country)<option value="{{ $country->id }}" @selected($country->id==18)>{{ $country->name }}</option>@endforeach</select><p class="error-message mt-1 hidden text-xs text-red-500">Please select a country</p></label>
   <label><span class="mb-1 block text-xs font-semibold text-slate-600">State Name <b class="text-red-500">*</b></span><input id="create_stateName" class="form-input h-10 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100" placeholder="e.g. Dhaka"><p class="error-message mt-1 hidden text-xs text-red-500">Please enter a state name</p></label>
   <label class="flex items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 p-3"><input type="checkbox" id="create_status" class="h-4 w-4 rounded text-blue-600" checked><span class="text-sm font-medium text-slate-700">Active</span></label>
  </form>
  <footer class="flex justify-end gap-2 border-t bg-slate-50 px-5 py-3"><button type="button" class="modal-close-create rounded-lg border px-4 py-2 text-xs font-semibold text-slate-600">Cancel</button><button id="createStateSubmit" type="button" class="rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white"><i class="fas fa-floppy-disk mr-1"></i>Save State</button></footer>
 </div>
</div>
